"""Generates the BuildConfig class that AGP used to produce."""

load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")

def _build_config_impl(ctx):
    out = ctx.actions.declare_file("BuildConfig.java")
    ctx.actions.write(
        out,
        """package {package};

/** Generated by //app:build_config; do not edit. */
public final class BuildConfig {{
    public static final String WORKOUTS_URL = "{workouts_url}";

    private BuildConfig() {{}}
}}
""".format(
            package = ctx.attr.package,
            workouts_url = ctx.attr.workouts_url[BuildSettingInfo].value,
        ),
    )
    return [DefaultInfo(files = depset([out]))]

build_config = rule(
    implementation = _build_config_impl,
    attrs = {
        "package": attr.string(mandatory = True),
        "workouts_url": attr.label(
            mandatory = True,
            providers = [BuildSettingInfo],
        ),
    },
)
